version: "3.3"

networks:
  kaond_testnet_network:
volumes:
  kaond_testnet_volume:

services:
  ethrpcgate_testnet:
    image: kaon/eth-rpc-gate:dev
    container_name: ethrpcgate_testchain
    build: 
        context: ../../
        cache_from:
          - golang:1.18-alpine
    ports:
        - "25996:25996"
    environment: 
        - KAON_RPC=http://${RPC_USER}:${RPC_PASSWORD}@kaon_testnet:51474
        - COMPOSE_PROJECT_NAME=testnet
    volumes:
        - ../standalone/myaccounts.txt:$GOPATH/github.com/kaonone/eth-rpc-gate/myaccounts.txt
        - ../../https:/https
        - ../../logs:/logs
    depends_on:
      - kaon_testnet
    command: --bind 0.0.0.0 --port 25996 --ignoreTransactions --accounts $GOPATH/github.com/kaonone/eth-rpc-gate/myaccounts.txt --dev --https-key /https/key.pem --https-cert /https/cert.pem
    networks:
      - kaond_testnet_network

  kaon_testnet:
    ports:
      - "51474:51474"
    image: kaon/kaon
    container_name: kaon_testnet
    environment: 
        - COMPOSE_PROJECT_NAME=testnet
        - RPC_USER=${RPC_USER}
        - RPC_PASSWORD=${RPC_PASSWORD}
    command: ["sh", "-c", "envsubst < /root/.Kaon/kaon.conf.testnet.template > /root/.Kaon/kaon.conf && kaond"]
    volumes:
      - kaond_testnet_volume:/root/.Kaon
      - ./kaon.conf.testnet.template:/root/.Kaon/kaon.conf.testnet.template
    networks:
      - kaond_testnet_network
