version: "3.3"

networks:
  kaond_regtest_network:
volumes:
  kaond_regtest_volume:

services:
  ethrpcgate_regtest:
    image: kaon/eth-rpc-gate:dev
    container_name: ethrpcgate_regtest
    build: 
        context: ../../
        cache_from:
          - golang:1.18-alpine
    ports:
        - "25996:25996"
    environment: 
        - KAON_RPC=http://${RPC_USER}:${RPC_PASSWORD}@kaon_regtest:51474
        - COMPOSE_PROJECT_NAME=regtest
    volumes:
        - ../standalone/myaccounts.txt:$GOPATH/github.com/kaonone/eth-rpc-gate/myaccounts.txt
        - ../../https:/https
        - ../../logs:/logs
    depends_on:
      - kaon_regtest
    command: --bind 0.0.0.0 --accounts $GOPATH/github.com/kaonone/eth-rpc-gate/myaccounts.txt --log-file /logs/gateLogs.txt --dev --https-key /https/key.pem --https-cert /https/cert.pem
    networks:
      - kaond_regtest_network

  kaon_regtest:
    ports:
      - "51474:51474"
    image: kaon/kaon
    container_name: kaon_regtest
    environment: 
        - COMPOSE_PROJECT_NAME=regtest
        - RPC_USER=${RPC_USER}
        - RPC_PASSWORD=${RPC_PASSWORD}
    command: ["sh", "-c", "envsubst < /root/.Kaon/kaon.conf.regtest.template > /root/.Kaon/kaon.conf && kaond"]
    volumes:
      - kaond_regtest_volume:/root/.Kaon
      - ./kaon.conf.regtest.template:/root/.Kaon/kaon.conf.regtest.template
    networks:
      - kaond_regtest_network
