version: "3.3"

networks:
  kaond_mainnet_network:
volumes:
  kaond_mainnet_volume:

services:
  ethrpcgate_mainnet:
    image: kaon/eth-rpc-gate:latest
    container_name: ethrpcgate_mainnet
    build: 
        context: ../../
        cache_from:
          - golang:1.18-alpine
    ports:
        - "25996:25996"
    environment: 
        - KAON_RPC=http://${RPC_USER}:${RPC_PASSWORD}@kaon_mainnet:51473
        - COMPOSE_PROJECT_NAME=mainnet
        - FLAG_HIDE_KAOND_LOGS=true
        - HIDE_TCP_LOGS=true
    volumes:
        - ../standalone/myaccounts.txt:$GOPATH/github.com/kaonone/eth-rpc-gate/myaccounts.txt
        - ../../https:/https
        - ../../logs:/logs
    depends_on:
      - kaon_mainnet
    command: --bind 0.0.0.0 --port 25996 --ignoreTransactions --accounts $GOPATH/github.com/kaonone/eth-rpc-gate/myaccounts.txt --https-key /https/key.pem --https-cert /https/cert.pem
    networks:
      - kaond_mainnet_network

  kaon_mainnet:
    ports:
      - "51473:51473"
    image: kaon/kaon
    container_name: kaon_mainnet
    environment: 
        - COMPOSE_PROJECT_NAME=mainnet
        - RPC_USER=${RPC_USER}
        - RPC_PASSWORD=${RPC_PASSWORD}
    command: ["sh", "-c", "envsubst < /root/.Kaon/kaon.conf.mainnet.template > /root/.Kaon/kaon.conf && kaond"]
    volumes:
      - kaond_mainnet_volume:/root/.Kaon
      - ./kaon.conf.mainnet.template:/root/.Kaon/kaon.conf.mainnet.template
    networks:
      - kaond_mainnet_network
