version: "3.3"
services:
  ethrpcgate:
    image: kaon/eth-rpc-gate:dev
    build:
      context: ../../
      dockerfile: ./Dockerfile
      cache_from:
        - golang:3.16-alpine
        - kaon/eth-rpc-gate:dev
    ports:
      - "25996:25996"
    environment:
      - KAON_RPC=http://kaon:kaonpass@kaon:51474
    volumes:
      - ../../:/src:ro
    depends_on:
      - kaon
    command: --bind 0.0.0.0 --accounts /src/myaccounts.txt --dev
  kaon:
    ports:
      - "51474:51474"
    image: kaon/kaon-seeded
    build:
      context: ../../docker
      dockerfile: ./kaon-seeded.Dockerfile
      cache_from:
        - kaon/kaon-seeded
    container_name: kaon_seeded_testchain
    command: kaond -testnet -rpcport=51474 -port=5778 -logevents -logtimestamps -printpriority -txindex -txrlpindex -daemon -server -listen -txindex -addrindex -rpcbind=0.0.0.0:51474 -rpcallowip=0.0.0.0/0 -rpcuser=kaon -rpcpassword=kaonpass -deprecatedrpc=accounts
  openzeppelin:
    image: kaon/eth-rpc-gate-openzeppelin
    build:
      context: .
      dockerfile: ./openzeppelin.Dockerfile
      cache_from:
        - kaon/eth-rpc-gate-openzeppelin
    environment:
      - GENERATE_TO_ADDRESS=azoZzNyhcbcTuytesg2dw8AY6p5pZCpZZj
    depends_on:
      - ethrpcgate
    command: truffle test --network docker
